---
branch: master
repositoryUrl: https://github.com/msalman899/terraform-aws-athena
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/git"
    - - "@semantic-release/github"
